name: keepassxc
version: 2.2.0
grade: stable
summary: community driven port of the windows application “Keepass Password Safe”
description: |
  KeePassXC is an application for people with extremely high demands on secure
  personal data management. It has a light interface, is cross platform and
  is published under the terms of the GNU General Public License.
confinement: strict

apps:
  keepassxc:
    command: desktop-launch keepassxc
    plugs: [unity7, x11, opengl, gsettings, home, network, network-bind, removable-media, raw-usb]
    desktop: share/applications/keepassxc.desktop
  cli:
    command: keepassxc-cli
    plugs: [gsettings, home, removable-media, raw-usb]

parts:
  keepassxc:
    source: .
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_TESTS=OFF
      - -DWITH_XC_AUTOTYPE=ON
      - -DWITH_XC_HTTP=ON
      - -DWITH_XC_YUBIKEY=ON
    build-packages:
      - g++
      - libgcrypt20-dev
      - libqt5x11extras5-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - zlib1g-dev
      - libxi-dev
      - libxtst-dev
      - libyubikey-dev
      - libykpers-1-dev
    after: [desktop-qt5]
  desktop-qt5:
    # Redefine stage packages to work with Ubuntu 17.04
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
